version: "3.2"
services:
  db:
    image: postgres:13-alpine
#    volumes:
#      - ${PWD}/db/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - 10000:5432
    environment:
      POSTGRES_USER: registrar
      POSTGRES_PASSWORD: test
      POSTGRES_DB: registrar

  registrar:
    image: registrar:2.0-SNAPSHOT
    volumes:
      - ${PWD}/config:/opt/config
    env_file:
      .env
    ports:
      - 8080:8080
    links:
      - db:db
